# Generated by Django 4.2 on 2026-06-15 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_date', models.DateField(help_text='The date this token is valid for')),
                ('expires_at', models.DateTimeField(help_text='When this token expires')),
                ('is_active', models.BooleanField(default=True, help_text='Admin can deactivate to revoke token')),
                ('scan_count', models.PositiveIntegerField(default=0, help_text='Total number of times this QR has been scanned')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_qr_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
